### ISSUE TITLE
Input randomly dies on ITG2 dedicab.

### ISSUE THREAD

**Issue by karai17** [djpohly/piuio#10]
I just installed a fresh system in my dedicab running Fedora 22 and StepMania 5.0.9. PIUIO seems to crash at random intervals while playing the game. My keyboard still works and pressing the buttons on the cab light up, but all cab/pad input dies. I have to restart StepMania and/or reboot the cab to get it working again.

**Comment by karai17** [comment]
A small update: The PIUIO has frozen a few more times while my sister was using the cab, one time in the middle of a song. The pad lights froze, too.

**Comment by djpohly** [comment]
Hm, this could be a number of things.  It would be useful to know if the system is still running when it happens (i.e. can you ssh in or use sysrq keys?) or if it's completely locked, and any kernel logs or stacktraces if it hangs/crashes.  If there is some error condition that the module does not handle, then yes that should be fixed here, but it could also be other bigger problems.

Is it maybe possible that there is a problem with the connection of the device to the computer, or that the computer needs a bigger power supply?  (@dguzek, does this sound like the power supply issues you saw once upon a time?)

Another possible diagnostic is removing this module and running another program which exercises the PIUIO card in a different way (e.g. libusb) to see if the module can be ruled out as a cause.

**Comment by karai17** [comment]
The game still functions, just not the PIUIO. I can still play with the keyboard so I don't think the system is locking up.

I am currently using a 500w PSU until I can get my molex->SATA adapter to use the official Boxor PSU so I doubt I am having trouble with power. I'll admit that the PIUIO is not sitting flush in a PCI slot since the mobo I bought ended up not having a PCI slot, but since the PIUIO doesn't actually connect to the mobo this should not be a problem.

**Comment by karai17** [comment]
An update: I just got a call from my sister saying the input died again. Without rebooting the machine, I had her close StepMania and run `jstest /dev/input/js0` in a terminal. She said all the input still seemed to be working. Restarting StepMania (without rebooting the machine) worked fine and she was able to continue playing.

**Comment by djpohly** [comment]
Sounds like the device is getting disconnected from the system (for whatever reason: bad connection, insufficient power, electrical short, etc.) and then reconnected.  SM doesn't reload joysticks when they are replugged.

Take a look through the output of `dmesg` to see if there are messages about the piuio device being connected/disconnected.  There might be other information nearby which gives an idea of what the problem is.

**Comment by karai17** [comment]
I have gone through and reconnected all connexions in the pc. So far there seems to be no more disconnecting going on. I will close this issue for now and update if it is continues to happen.

**Comment by karai17** [comment]
![](http://imgur.com/hVEEztU)

Input died again, I had my sister take a pic of the output from `dmesg`.

**Comment by dguzek** [comment]
It is possible that the PIUIO card is shorting out.  The ITG2 cabinet I maintain used to do that (and input would die) from people touching the menu buttons until we had a electrical engineering student properly ground the cabinet internals.

**Comment by karai17** [comment]
It's possible, but I don't think it is very likely. The cabinet and all buttons work fine, it just seems to randomly die. It can die several times a day, or work great for a week or so. If it were an electrical issue I'd expect it to be more consistent.

**Comment by dguzek** [comment]
For what it's worth, it was very inconsistent for us, almost exactly like you're describing.  

It still does happen, maybe twice a year now, but much, much less than years ago.

**Comment by karai17** [comment]
I'll have my friend take a look at the cab with a multimeter this evening.


---
Landon Manning
lmanning17@gmail.com

**Comment by djpohly** [comment]
Explanation of dmesg log:

1. PIUIO is getting physically or electrically disconnected from the computer.
2. Thread for input on the disconnected device (callback/resubmit lines) notices that it has disappeared.  Gives errors/warnings because the disconnect is probably not intentional, but it won't break the driver.
3. PIUIO becomes physically or electrically reconnected and is registered as a *new* logical device (correct behavior for removable devices).
4. Driver registers the new logical device as input.
5. USB threads for (I assume the old) input device are shut down, due either to X closing it or to the kernel calling its "disconnect" handler.

It seems to me that the driver is behaving exactly as it should given the circumstances.  IIRC StepMania does not handle disconnected/reconnected controllers (i.e. joysticks) particularly well though.

**Comment by karai17** [comment]
Thanks for the explanation. I am quite confident that the input is not
being physically disconnected, so perhaps it is an electrical issue after
all. Perhaps there is a common place I can start my search? I don't really
know much about that side of electronics so any more headway would be
appreciated.


---
Landon Manning
lmanning17@gmail.com

**Comment by karai17** [comment]
I'll close this as it is clear there is not a driver issue, but some sort of physical issue.

**Comment by concubidated** [comment]
I might as well add, I have the exact same issues on 3-4 cabs. Swapping USB ports and cables seemed to help, but still does happen every once in a while.

**Comment by concubidated** [comment]
@djpohly Just wanted to add another update. Grounding out the button board did not fix our issues, and it is still occurring very frequently on a couple of the cabinets.

I have now seen this problem on all 6 cabinets, Is there anyway to handle this issue in the driver? Anyway to make it NOT come up as a new input device when disconnected for a split second?

**Comment by karai17** [comment]
Long overdue, but I want to note that I have since fully resolved this issue. The issue was that the USB-B cable that connects the PIUIO card to the PC was faulty and replacing it solved the disconnects. This is apparently a known issue with the cables that originally came with the dedicab and boxor replacement units.

To any future readers of this issue, make sure to swap out the USB cable while troubleshooting as it could likely be your issue.
