### ISSUE TITLE
Lights are swapped between players

### ISSUE THREAD

**Issue by karai17** [djpohly/piuio#11]
I just installed a fresh system in my dedicab running Fedora 22 and StepMania 5.0.9. The lights on my player 1 pad light up when I press the player 2 buttons, and v/v. I'm unsure if this is a PIUIO problem, if there is a setting I need to tweak, or if the people who owned the cab before me have the JAMMA wired incorrectly. I won't be able to test the JAMMA connexions any time soon as my cab is in a different town, but I just wanted to know if this issue has cropped up before and if there is a software fix?

**Comment by djpohly** [comment]
This module only presents a generic interface for reading inputs and controlling outputs.  What these are used for, and how they map to each other, depends on the software that accesses the module.

(Unofficially: I'd guess it's the wiring, but really someone with actual time should contribute a patch at https://github.com/stepmania/stepmania/issues/253 :smile:)

**Comment by karai17** [comment]
I'll have to check the wiring next time I have access, then.

**Comment by karai17** [comment]
Just to note, swapping the plugs in the JAMMA board fixed the lights. :)
