### ISSUE TITLE
Provided Makefile does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by ianklatzco** [djpohly/piuio#14]
`sudo make install` causes:

```
make -C /lib/modules/4.15.0-38-generic/build M=/home/wendy/piuio/mod modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-38-generic'
  INSTALL /home/wendy/piuio/mod/piuio.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.15.0-38-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-38-generic'
```

Kernel signing stuff. SecureBoot isn't supported on my hardware, so I've been very ?????? as to why it doesn't work.

Fix, courtesy Rynker:
```
sudo make
sudo make install # fails so this can probably be omitted
sudo depmod -a # Probe all modules.
sudo modprobe piuio # Insert it.
```

**Comment by ianklatzco** [comment]
(now that the tournament's over):

I'm mostly posting this issue here so that it'll come up when others google for it. I'm not sure if there's an easy fix / if you intend to anytime soon.

I'm curious about how the kernel makefiles work. I was thinking about changing kernel parameters to disable signing of compiled modules, but I think that'd require a complete recompile of my kernel and the other solution worked instead. I *think* that it didn't compiled signed on my machine?

And yet, the `sudo make install` failed, but I can't tell what it actually tried doing, since the Makefile in this repo is pretty barebones and I think it just passes off to the kernel Makefiles. Could someone clarify / point me at a nice resources for learning more?

**Comment by stympy9** [comment]
I have a same problem 

stympy@stympy:~/Descargas/piuio-master/mod$ sudo make install
make -C /lib/modules/4.18.0-25-generic/build M=/home/stympy/.local/share/Trash/files/piuio-master/mod modules_install
make[1]: se entra en el directorio '/usr/src/linux-headers-4.18.0-25-generic'
  INSTALL /home/stympy/.local/share/Trash/files/piuio-master/mod/piuio.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.18.0-25-generic
make[1]: se sale del directorio '/usr/src/linux-headers-4.18.0-25-generic'


No such file or directory: ../crypto/bio/bss_file. ??? ¿is a ssl problem ?

**Comment by djpohly** [comment]
Have you checked to see if the module was actually installed?

Here is what I get when I do the install step (using `DESTDIR` to install to the current directory for my own testing):
```
$ make DESTDIR="$PWD" install
make -C /lib/modules/5.2.2-artix1-1-ARTIX/build M=/home/djpohly/src/piuio/mod modules_install
make[1]: Entering directory '/usr/lib/modules/5.2.2-artix1-1-ARTIX/build'
  INSTALL /home/djpohly/src/piuio/mod/piuio.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.2.2-artix1-1-ARTIX
depmod: WARNING: could not open modules.order at /home/djpohly/src/piuio/mod/lib/modules/5.2.2-artix1-1-ARTIX: No such file or directory
depmod: WARNING: could not open modules.builtin at /home/djpohly/src/piuio/mod/lib/modules/5.2.2-artix1-1-ARTIX: No such file or directory
make[1]: Leaving directory '/usr/lib/modules/5.2.2-artix1-1-ARTIX/build'
$ find lib/modules
lib/modules
lib/modules/5.2.2-artix1-1-ARTIX
lib/modules/5.2.2-artix1-1-ARTIX/modules.dep.bin
lib/modules/5.2.2-artix1-1-ARTIX/modules.symbols.bin
lib/modules/5.2.2-artix1-1-ARTIX/modules.dep
lib/modules/5.2.2-artix1-1-ARTIX/modules.builtin.bin
lib/modules/5.2.2-artix1-1-ARTIX/modules.softdep
lib/modules/5.2.2-artix1-1-ARTIX/modules.symbols
lib/modules/5.2.2-artix1-1-ARTIX/modules.alias
lib/modules/5.2.2-artix1-1-ARTIX/modules.devname
lib/modules/5.2.2-artix1-1-ARTIX/updates
lib/modules/5.2.2-artix1-1-ARTIX/updates/piuio.ko.xz
lib/modules/5.2.2-artix1-1-ARTIX/modules.alias.bin
```
Note that the SSL error appears, but also the INSTALL and DEPMOD steps both execute, and their products appear in the install directory.  The error seems only to indicate that it couldn't add a cryptographic signature to the kernel module (which, I suspect, isn't something that most would be concerned about).

Based on what I've observed, I'm going to close the issue, but feel free to reopen it if there is a problem that I'm not seeing.  I'd happily accept a PR that updates the README to mention specifically that this error is not a problem.

**Comment by stympy9** [comment]
I would add

1. Generate key using it with the kernel module you want to sign

    openssl req -new -x509 -newkey rsa:2048 -keyout signing_key.pem -outform DER -out signing_key.x509 -nodes -subj "/CN=Owner/"

2. Copy the generated keys to /usr/src/kernels/$(uname -r)/certs/

    cp signing_key.x509 signing_key.pem /usr/src/kernels/$(uname -r)/certs/

3. Compile module sources by following appropriate steps

    make & make install

**Comment by djpohly** [comment]
I reckon anyone who actually understands and needs cryptographic signing (not likely for this module's use cases) will recognize the error and be able to solve it themselves.  I've added a note that should clear up the confusion for anyone else.
