### ISSUE TITLE
piuio inconsistent with different builds

### ISSUE THREAD

**Issue by darknotezero** [djpohly/piuio#9]
hey there, 

so i have this hdd image of stepmania that i found that works out of box, running SM 5.0 beta 1.  i'm attempting to update to the most recent version of stepmania to take advantage of the simply love theme and also stay current.

when i grabbed the new version of piuio, i encountered the same error that now in the "closed ticket" area where you said that the kernel and/or Linux version is too old and the legacy piuio should be used instead. 

the thing is, the legacy version of piuio is already running on the machine - if i try to run one of the two sm builds installed in the machine running the SM 5.0 beta 1, pads work with no issues, but if i try to run the version I installed, 5.0.7, piuio is not recognized as a source during test input, so the pads are not responsive at all.

any clue on the issue here?  should I try to remake the legacy piuio build and scratch the one that's there,  or is that a waste of time?  is there something else I'm missing? 

many thanks for your work on this!

**Comment by djpohly** [comment]
Could be a lot of things.  If you're going to be upgrading kernel drivers, you should make sure to have some knowledge about your distro, packages, kernel, and how modules work.  Random HDD images for easy-to-install open-source software are usually more miss than hit.  If you still want to go that route, some troubleshooting questions:

* What distro and kernel version are you running?
* Is the PIUIO module installed as a package?
* Did you unload the old PIUIO module before testing?
* Did you uninstall the old PIUIO module from the filesystem?
* Did you install the new PIUIO module to the filesystem?
* Is the new module loaded?
* Does the PIUIO appear as an event device in /dev/input?
* Do you have the X11 joystick driver installed?
* Does the PIUIO appear as an input device to xinput?
* What are your InputDrivers in StepMania set to?

**Comment by darknotezero** [comment]
Yeah, my knowledge of Linux prior to starting this project was pretty much nil (although i'm a hack computer programmer), so i know i'm basically running around blind.  That's part of why i'm doing this, because i want to learn more about it, learn more about even what questions i should be asking myself when faced with issues.

I don't know how to answer all of those questions, but i can answer a few:

- The kernel being run is Mint 13.
- I did not unload the old PIUIO module before testing nor did i uninstall it.
- I attempted to install the new PIUIO module into the system and when i tried to compile it it came back with an error and did not actually compile/make a .ko file anywhere.  That's the error that is the same as the closed ticket when a different user tried to compile under an old version of debian.
- I'm pretty sure that i do *not* have the x11 joystick driver installed, but i'm only 80% sure about that.

The big question to answer is the last one - The InputDrivers in the preferences.ini file was set to nothing - I thought that that was fine since the preinstalled SMs worked fine under that configuration.  Yesterday I actually decided to try to forcefeed the issue by putting "PIUIO" as the InputDriver and the LightsDriver, and lo and behold the pads worked (although it made the QWERTY keyboard stop working).

So now i have it essentially functioning the way that i want to, but I kind of feel the need to update the kernel to something more current because i get the impression that Mint 13 is pretty old and i want to stay current and maybe try to get the new PIUIO driver to compile and then load it in.  Even if i break something, i can always fall back on the original HDD and start over, and particularly start over with new knowledge.  I don't know if that's a sound plan or if it's plain stupid. :)

i'll find some of the other answers to your questions for completion - for myself more than anything else because i need and want to learn more about linux than i currently do.

**Comment by dguzek** [comment]
It may be worth noting that using
```ini
InputDrivers=PIUIO
```

in your StepMania.ini only worked with the 0.1 release of this driver.  From 0.2 on, you should use

```ini
InputDrivers=LinuxEvent,x11 
LightsDriver=Linux_PIUIO_Leds 
```

to support input and lights.

**Comment by darknotezero** [comment]
awesome.  thanks again for your work and your help!
